workflows:
  ios-build:
    name: Meow iOS Build

    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Resolve Swift Packages
        script: |
          xcodebuild \
            -resolvePackageDependencies \
            -project meow-ios.xcodeproj

      - name: Build App (No Sign)
        script: |
          xcodebuild \
            -project meow-ios.xcodeproj \
            -scheme meow-ios \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - "**/*.app"
      - "**/*.xcarchive"
      - "**/*.xcresult"
