workflows:
  ios-build:
    name: Meow iOS Build

    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Show repository structure
        script: |
          pwd
          echo "========== ROOT =========="
          ls -la

          echo "========== XCODE FILES =========="
          find . -name "*.xcodeproj"
          find . -name "*.xcworkspace"

      - name: Show schemes
        script: |
          PROJECT=$(find . -name "*.xcodeproj" | head -n 1)

          if [ -z "$PROJECT" ]; then
            echo "No .xcodeproj found"
            exit 1
          fi

          echo "Project: $PROJECT"

          xcodebuild -list -project "$PROJECT"

    artifacts:
      - "**/*.xcresult"
